server/simulation/random.js
=> fixes: Generate random drone model names #1

server/simulation/random.js
Had some problems setting up gulp and running it.( My first ever try to commit on GitHub )
Wrote the function in visual studio code and used .run package to run it and see the results.
The function works as expected, but please try it on the actual server before merging!
=> Implemented randomRating() ISSUE : #3

code_of_conduct.md
First open source contribution! Yay!
=> Adding code of conduct. Closes #4

README.md
=> Added gitter link to README #11

test/specs/simulation.random.spec.js
Added tests to check randomDavAddress() for #18 
test to make sure that randomDavAddress() is returning string and is of length equal to 42
=> Added tests to check randomDavAddress()

package.json
I added a field to the file. Warning disappeared
All right?
=> Add repository field to package.json file. Issue #23

server/simulation/random.js
=> Generate random missions completed #26

server/simulation/random.js
Updated modelNames variable with new drone names -issue: #41
=> #41 Updated new drone model names

server/simulation/random.js
referenced from this [issue #24](https://github.com/DAVFoundation/missioncontrol/issues/24)
=> #24 added JSDoc comment block for randomMissionsCompleted

server/simulation/random.js
Added comments on random.js method randomManufacturerName() - issue #15
=> Added comment for generateRandomManufacturer method

server/lib/davIdIcon.js, test/specs/lib.davIdIcon.spec.js
Could you please review this pull request?
=> Create tests for DAV ID icon -issue #28

README.md
=> Added license badge on README #49

README.md
Updated appearance of gitter badge per issue #48
=> Update gitter badge in README

server/simulation/random.js
add jsdoc to function randomDroneModel in random.js #17
=> add jsdoc to function randomDroneModel in random.js #17

server/simulation/random.js
Hello TalAter,
this is my first PR so i hope i've done everything right.
I added JSDoc comment for the randomModelName function in server/simulation/random.js. It should close Issue #54
=> Added jsdoc to randomModelName(). Closes #54

test/specs/simulation.drone.spec.js
Added a spec to test the random drone generator generates an object with an id. Closes #56
First PR!
=> Add tests to check random drone generator. Closes #56

test/specs/simulation.drone.spec.js
Add unit test that ensures random drone generator returns an object with a 'model' attribute.
=> Random drone generator test/#60

server/lib/environment.js, server/server-web.js, server/store/redis.js, test/specs/lib.environment.spec.js
Should close #70 
Gotta love that beautiful all green screen on the first try 😃 🚀
=> refactored hasStore boolean into hasStore() function

test/specs/simulation.drone.spec.js
=> Adding test to check for missions_completed_7_days attribute

test/specs/lib.davIdIcon.spec.js, test/specs/simulation.drone.spec.js
=> #65 fix Add tests to check missions_completed attribute in random drone generator (first-timers-only)

test/specs/simulation.random.spec.js
Added tests missionsCompleted7Days should be a positive integer that is less than or equal to the value of missionsCompleted
=> Issue #31 add tests to check missionsCompleted7Days value is in required range Issue

server/lib/davIdIcon.js, test/specs/lib.davIdIcon.spec.js
fixes #61
Hey @TalAter, Thanks for your patience 🙇 Sorry, got busy with other stuff and it took a while.
* Let me know if its the right way to raise an exception. 
* Once approved I will create the first-timers issue for writing the test.
🙂
=> worked on refactoring getDavIdIconUrl

test/specs/simulation.random.spec.js
Added test using regExp to match the specified requirements of start chars of **0x** followed by 40 hex dec chars
New test on randomDavAddress string
Ran **npm test**
- [X ] My code follows the code style of this project.
- [ X] I have read the **CONTRIBUTING** document.
- [X ] I have added tests to cover my changes.
- [ X] All new and existing tests passed.
=> #82 add test to verify randomDavAddress() works correctly

test/specs/simulation.vehicles.spec.js
- tests that it returns an array with a length similar to the vehicleCount argument
- tests that it returns an array of objects containing id, model, icon, coords, rating, missions_completed, missions_completed_7_days
https://github.com/DAVFoundation/missioncontrol/issues/85
=> Adds test for generateRandomVehicles()

server/server-web.js, server/simulation/drone.js, server/store/bids.js, server/store/missions.js, server/store/requests.js, server/store/vehicles.js, test/specs/simulation.vehicles.spec.js
Issue https://github.com/DAVFoundation/missioncontrol/issues/91
=> feat: added route to cancel request

server/server-web.js, server/simulation/drone.js, server/store/bids.js, server/store/missions.js, server/store/vehicles.js, test/specs/simulation.vehicles.spec.js
Issue https://github.com/DAVFoundation/missioncontrol/issues/89
=> feat: stops storing bids in memory indefinitely

docker-compose.yml, package.json, server/lib/elevation.js
Issue [#57](https://github.com/DAVFoundation/missioncontrol/issues/57)
Added ground elevation by coordinates using Google Elevation API. 
TODO: 
- query Google Elevation API with batches of 512 locations. According to API the locations amount per request is 512.
- add tests
=> Create function to make sure drones don't fly into ⛰

server/config/index.js, server/store/bids.js
=> Added bids ttl value to the external config file #101

server/config/index.js, server/store/requests.js
Replaced a hardcoded number with a call to the config file.
Replaced a magic number in server/store/requests.js with a call to server/config/index.js
[Issue](https://github.com/DAVFoundation/missioncontrol/issues/102)
Placing constants in a config file makes the code more maintainable, and easier to refactor.
The changes pass the tests, and do not break the server. When the ttl was printed to the console,
it matched the expected result of 43200.
=> Issue #102: Replace hardcoded value

server/simulation/vehicles.js, test/specs/simulation.vehicles.spec.js
Added a test in the simulation.vehicles.spec.js for the randomBid() function
https://github.com/DAVFoundation/missioncontrol/issues/86
The change is required to test that the randomBid() function is outputting an object with a price containing a float. 
I tested my changes by running an "npm test" and all tests passed, including the newly added test.
=> Added a test for the randomBid() function #86

server/store/vehicles.js
Add `coords` object for vehicle from server.
=> chore: created coords object in vehicles

test/specs/simulation.vehicles.spec.js
Added The testcase.
Fixes [#112](https://github.com/DAVFoundation/missioncontrol/issues/112)
=> Test the output of randomBid() contains time_to_pickup (#112)

package.json
Add homepage field to package.json
=> #114 - Add homepage field to package.json

npm-shrinkwrap.json, package.json, server/controllers/RequestController.js, server/controllers/StatusController.js, server/middleware/getOrCreateUser.js, server/simulation/missionProgress.js
Also fixed paths required in middleware and controllers.
=> feat: track delivery time and transition mission + vehicle between stages

package.json
=> Add bugs field to package.json #115 

LICENSE
=> #116: Changed license date to 2018

test/specs/simulation.random.spec.js
I added a test in the simulation.random.spec.js file to test the output of randomCoords(). It tests it against the given coordinates using the haversine formula. After retrieving the distance between the given coordinates and returned coordinates the distance must be less than or equal to the given radius. 
https://github.com/DAVFoundation/missioncontrol/issues/84
It helps us make sure the randomly generated coordinates are not outside the intended range. 
I ran npm test in my projects and all tests passed. I also tested some values that got passed against this online calculator: https://www.movable-type.co.uk/scripts/latlong.html
Sample output (note that the output in my console is in meters):
=> Added a test for randomCoords() using the haversine formula. #84

package-lock.json, package.json, test/helpers/index.js, test/specs/lib.davIdIcon.spec.js
Extracted checkIfAbsoluteURL() to a helper file.
Created a helper file at test/helpers/index.js.
Extracted checkIfAbsoluteURL() to it.
Referenced helper file at test file.
https://github.com/DAVFoundation/missioncontrol/issues/129
npm test
Passed all the 5 tests.
=> Dev tweak test

server/controllers/MissionController.js
To make sure that `/mission_command` responds with the latest mission and vehicle
=> chore: updated mission and vehicle in command, MissionController

package-lock.json
I fixed the problem where `npm install` was failing.
=> Fixed dependency issue

server/config/index.js, server/store/vehicles.js
Added a ttl to the vehicles store so that vehicles will expire in 24 hours. The expire is being set in `addNewVehicle()` and `getVehicle()`. 
https://github.com/DAVFoundation/missioncontrol/issues/88
It is a wait of resources to have a massive amount of randomly generated vehicles being stored forever. Setting an expire time will open up space for newly generated vehicles. 
I ran `npm test` and all tests passed. I also did `console.log(redis.ttl(`vehicles:${id}`));` in `getVehicle()` and it returned true consistently.
=> Added ttl to vehicles. #88

test/specs/simulation.random.spec.js
Added test to simulation.random.spec to verify randomRating Output
#83 
This tests out the randomRating output to ensure that it returns a floating point number between 4.3 and 5.0
Ran the npm test
- [ X] New feature (non-breaking change which adds functionality)
- [ X] My code follows the code style of this project.
- [ X] I have read the **CONTRIBUTING** document.
- [ X] I have added tests to cover my changes.
- [ X] All new and existing tests passed.
=> Added test to verify randomRating Output #83

server/controllers/StatusController.js, server/simulation/missionProgress.js
Updates mission status to `completed` when completed.
=> fix: chore: set mission to complete when complete.

README.md
Removed the redundant license footer from readme.md
=> #164 Removed redundant license footer

server/store/needs.js
#155 
I changed ```redis.expire(`needs:${needId}`, config('needs_ttl'));``` to ```setNeedTTL(needId);``` and i created a ```const const setNeedTTL = async needId => redis.expire(`needs:${needId}`, config('needs_ttl'));```
#155 
It solves code duplication.
- [ X] My change requires a change to the documentation.
=> issue #155 : Refactor setting TTL in need.js

test/specs/simulation.vehicles.spec.js
Added test cases to check if randomBid throws an error when it gets either 0, 1, or 2 parameters instead of the intended 3 parameters.
https://github.com/DAVFoundation/missioncontrol/issues/171
See description 
Added tests
=> Added test cases making sure randomBid gets 3 parameters #171

CONTRIBUTING.md
Added instructions for temporarily fixing error mentioned in #162
=> add: Instructions for flusing redis cache

server/controllers/constraints/need/create.js, server/store/missions.js
Added pickup_address field on server. This feature is needed for fixing [issue 92](https://github.com/DAVFoundation/missions/issues/92) from [missions](https://github.com/DAVFoundation/missions) source code
[Issue 92](https://github.com/DAVFoundation/missions/issues/92) from mission repository
This change was need in order to show the actual address on the arrival notification.
=> Added pickup_address field in store and constraints

server/gradd/gradd.js
=> fixed URL in email

package.json
=> changed licence to 'MIT'

k8s/package.json
#203 
Changed ISC to MIT in package.json file
=> Update License 

src/App.test.ts
- Added parent suite to remove duplicated beforeEach code
- Refactored using of promises to asyn/await
=> Addressed TODOs in App tests

src/provider/RideHailingProvider.test.ts
Test load and save functionality of the ride_hailing provider
=> Add a few tests for ride_hailing provider

src/App.test.ts, src/provider/VehicleRiderProvider.test.ts
- Test load and save functionality of the vehicle_rider provider
- Test the HTTP app for proper unhealthy status
=> Tests for vehicle_rider provider and app unhealthy status

src/App.test.ts
Test for connected Cassandra status to check that it contains host list of length 1
=> Add test for connected Cassandra status to check number of hosts
